environment:
  nodejs_version: "8"

  matrix:
    - {}
    - {SPELLCHECKER_PREFER_HUNSPELL: true}

install:
  - ps: Install-Product node $env:nodejs_version
  - npm --msvs_version=2013 install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
